import numpy as np
from mayavi import mlab
from scipy import special


def sphere_projection(_R, _I):
    """
    Visualising the magnetic field and using as a sphere as a volume
    element to analyse the field and its magnetic field lines
    """
    # Generating the 3D space
    x, y, z = [i.astype(np.float32) for i in
               np.ogrid[-20:20:200j, -20:20:200j, -20:20:200j]]

    r = np.sqrt(x ** 2 + y ** 2)
    x_trans = x / r  # cos(a)
    y_trans = y / r  # sin(a)

    E = special.ellipe((4*_R*r)/((_R+r)**2 + z**2))  # special ellipse E
    K = special.ellipk((4*_R*r)/((_R+r)**2 + z**2))  # special ellipse K
    Bz = _I / (2*np.pi*np.sqrt((_R+r)**2 + z**2)) * (K + E * (_R**2 - r**2 - z**2)/((_R-r)**2 + z**2))

    # When r=0 there is a ZeroDivisionError for Br
    try:
        Br = (_I / (2 * np.pi * r)) * (z / (np.sqrt((_R + r) ** 2 + z ** 2))) * (
                    -K + E * ((_R ** 2 + r ** 2 + z ** 2) / ((_R - r) ** 2 + z ** 2)))
    except ZeroDivisionError:
        Br = 0
    # When the current I equals 0 there is no magnetic field
    if _I == 0:
        return 'WARNING: When I=0, \n There is no magnetic field generated'

    else:
        mlab.close(all=True)
        Bx, By = x_trans * Br, y_trans * Br
        fig = mlab.figure(1, size=(500, 500), bgcolor=(1, 1, 1), fgcolor=(0, 0, 0))
        field = mlab.pipeline.vector_field(Bx, By, Bz)
        magnitude = mlab.pipeline.extract_vector_norm(field)
        contours = mlab.pipeline.iso_surface(magnitude,
                                             contours=[0.001, 0.8, 3.8, 4.0],
                                             transparent=True,
                                             opacity=0.6,
                                             colormap='YlGnBu',
                                             vmin=0, vmax=0.5)

        field_lines = mlab.pipeline.streamline(magnitude, seedtype='sphere',
                                               integration_direction='both',
                                               transparent=True,
                                               opacity=0.3,
                                               colormap='jet',
                                               vmin=0, vmax=0.5)

        field_lines.stream_tracer.maximum_propagation = 150.
        field_lines.seed.widget.radius = 5.5
        mlab.view(azimuth=42, elevation=73, distance=104)
        mlab.title('Visualisation of the magnetic field\n generated by a current loop')
        sc = mlab.scalarbar(field_lines, title='Field Strength [T]', orientation='vertical', nb_labels=4)
        sc.scalar_bar_representation.position2 = np.array([0.1, 0.8])
        sc.scalar_bar_representation.position = np.array([0.88374749, 0.14342105])
        # del x, y, z, r, E, K, Br, Bx, By, Bz


sphere_projection(1, 1)
mlab.show()


p1_list = [[95, 100.5, 100], ]
p2_list = [[105, 100.5, 100], ]
contour_list = [[0.001, 0.8, 3.8, 4.0, 4.5], [0.001, 0.5, 4.0, 5.0], [0.001, 0.5, 4.5, 5.5], [0.001, 0.8, 3.8]]
